Appstore.connect refactor
holochain/launcher-tauri pull request #189
Opened 2023-08-14 18:26 UTC by mrruby

2023-08-15 08:52 UTC, matthme commented on src/appstore/appstore-interface.ts
> +            const result = await appWebsocket.callZome({
The type is actually `Response<boolean>` there. I was just too lazy to look the type up when I wrote this peace of code but I think it would be nice to have the type there instead of removing it because of the eslint complaint about "any".

2023-08-15 08:53 UTC, matthme commented on src/appstore/appstore-interface.ts
> +            const result = await appWebsocket.callZome({
That's where I looked it up by the way: https://github.com/holochain/portal-dna/blob/14ad357ae42ee7451848a249a7e32acb40519dbc/zomes/portal_api/src/lib.rs#L170

2023-08-15 09:16 UTC, mrruby commented on src/appstore/appstore-interface.ts
> +            const result = await appWebsocket.callZome({
Do we need to type it ```Response<boolean>```? 
I don't see the compiler complaining about getting it explicitly

2023-08-15 15:37 UTC, matthme commented on src/store/index.ts
> +    idConnectedToWebSocket(state) {
is this a typo and should be `isConnectedToWebSocket`? Or is it on purpose?

2023-08-15 15:37 UTC, matthme commented on src/views/AppStore.vue
>        this.holochainId = holochainId;
Those two lines need to become part of `fetchApps()` now becuase they strictly need to be run (otherwise the app download fails) while connecting to the appwebsocket is only necessary if it is not already part of the store.

2023-08-15 15:37 UTC, matthme commented on src/views/AppStore.vue
>        this.holochainId = holochainId;
In other words, whenever [this](https://github.com/holochain/launcher/blob/453136802728aa014473e98ba6442edaab6b9691/src/views/AppStore.vue#L412) line is being called, `this.holochainId` must be defined

2023-08-15 15:37 UTC, matthme commented on src/store/index.ts
> +      const appWebsocket = await AppWebsocket.connect(
I think it would be nice to add the types here:
```
      const holochainId: HolochainId = getters["holochainIdForDevhub"];
      const port: string | undefined = getters["appInterfacePort"](holochainId);
      const appWebsocket: AppWebsocket = await AppWebsocket.connect(
```

2023-08-15 15:37 UTC, matthme commented on src/appstore/appstore-interface.ts
> +            const result = await appWebsocket.callZome({
It's less about the compiler but more about that I like to know the types when reading (or changing) the code. Otherwise I have to go figure it out by looking in the rust code of whathever zome that zome call is part of to know what I get back.

2023-08-15 15:37 UTC, matthme commented on package.json
> +    "start:dev": "npm run build:ui && npm run tauri dev",
The `npm run build:ui` part is actually not necessary to run it in dev mode as far as I know and it will make it slower.
It is however required for running it via `cd src-tauri && cargo run`. So maybe we can add another script like so:
`    "start:dev2": "npm run build:ui && cargo run --manifest-path ./src-tauri/Cargo.toml",`
which runs without hot-reloading but with the ability to open apps within the Launcher.

2023-08-16 10:53 UTC, mrruby commented on package.json
> +    "start:dev": "npm run build:ui && npm run tauri dev",
But we have this in dev documentation, can we need to change it?
`
### Compiles and hot-reloads for development
````bash
npm run build:ui
npm run tauri dev
```
`

2023-08-16 11:14 UTC, matthme commented on package.json
> +    "start:dev": "npm run build:ui && npm run tauri dev",
Yes you're right, I think that first line there is not necessary.We could also think about changing that line to `npm run start:dev` if we add that script...

2023-08-16 11:14 UTC, matthme commented on package.json
> +    "start:dev": "npm run build:ui && npm run tauri dev",
Ah I see you did that already

2023-08-16 11:18 UTC, mrruby commented on src/appstore/appstore-interface.ts
> +            const result = await appWebsocket.callZome({
fixed

2023-08-16 11:18 UTC, mrruby commented on src/store/index.ts
> +    idConnectedToWebSocket(state) {
fixed

2023-08-16 11:18 UTC, mrruby commented on src/views/AppStore.vue
>        this.holochainId = holochainId;
fixed

2023-08-16 11:19 UTC, mrruby commented on src/store/index.ts
> +      const appWebsocket = await AppWebsocket.connect(
fixed

2023-08-16 11:21 UTC, mrruby commented on package.json
> +    "start:dev": "npm run build:ui && npm run tauri dev",
to make it not to complex if it is one line, let's leave it as it is and I made another script

2023-08-16 11:25 UTC, matthme requested changes

2023-08-16 11:25 UTC, matthme commented on package.json
> +    "dev:quasi-prod": "npm run build:ui && cd src-tauri && cargo run",
Is it indeed twice the same line here or is this a git glitch?

2023-08-16 11:25 UTC, matthme commented on package.json
> +    "dev:quasi-prod": "npm run build:ui && cd src-tauri && cargo run",
And I think it would be better to have the command like this:
`   "dev:quasi-prod": "npm run build:ui && cargo run --manifest-path ./src-tauri/Cargo.toml",`
Other wise the current working directory will change when running the command which I think is inconvenient.

2023-08-16 11:45 UTC, matthme approved these changes

2023-08-16 11:45 UTC, merged