Launcher API and notifications
holochain/launcher-tauri pull request #205
Opened 2023-09-29 14:10 UTC by matthme

This is a larger PR that adds an API for happs to call, specifically at the moment in order to send notifications (OS, systray and to the admin UI).

Relevant changes:

* adds an npm package to be used by happs to make calls to the launcher
* adds an api-scripts package containing js code that injects the API into the happ window's window object (thus providing a decoupling layer between the tauri API and the launcher API)
* makes sure that happ windows are (and remain) opened in the backround on startup of the launcher such that UIs are able to send notifications
* Adds affordances to add the option to have different notification settings per happ
* displays notifications as OS notifications, as dots in the systray icon and in the Launcher view, depending on the urgency level of the notification

2023-09-30 12:26 UTC, mrruby requested changes

2023-09-30 12:26 UTC, mrruby commented on src/utils.ts
>  }
Generally I would do something more declarative for this file to make it easier to read, something like (you would need to solve some of the any issues from my solution):




```
const getLocalStorageItem = (key: string): any => {
  const item: string | null = window.localStorage.getItem(key);
  return item ? JSON.parse(item) : [];
};

const setLocalStorageItem = (key: string, value: any): void => {
  window.localStorage.setItem(key, JSON.stringify(value));
};

export function storeHappNotifications(
  notifications: Array<HappNotification>,
  appId: string
): Array<HappNotification> {
  const unreadKey = `happNotificationsUnread#${appId}`;
  const unreadNotifications = [
    ...new Set([...getLocalStorageItem(unreadKey), ...notifications]),
  ];
  setLocalStorageItem(unreadKey, unreadNotifications);

  notifications.forEach((notification) => {
    const timestamp = notification.timestamp;
    const daysSinceEpoch = Math.floor(timestamp / 8.64e7);
    const sameDateKey = `happNotifications#${daysSinceEpoch}#${appId}`;
    const notificationsOfSameDate = [
      ...new Set([...getLocalStorageItem(sameDateKey), notification]),
    ];
    setLocalStorageItem(sameDateKey, notificationsOfSameDate);
  });

  return unreadNotifications;
}

export function readUnreadHappNotifications(
  appId: string
): Array<HappNotification> {
  return getLocalStorageItem(`happNotificationsUnread#${appId}`);
}

export function clearHappNotifications(appId: InstalledAppId) {
  const unreadNotifications = getLocalStorageItem(
    `happNotificationsUnread#${appId}`
  );
  const unreadNotificationsCleared = unreadNotifications.filter(
    (notification) => !!notification.customCountReset
  );
  setLocalStorageItem(
    `happNotificationsUnread#${appId}`,
    unreadNotificationsCleared
  );
}

export function resetHappNotificationCount(
  appId: InstalledAppId,
  notificationIds: Array<NotificationId>
) {
  const unreadNotifications = getLocalStorageItem(
    `happNotificationsUnread#${appId}`
  );
  const unreadNotificationsCleared = unreadNotifications.filter(
    (notification) =>
      !notification.customCountReset ||
      !notificationIds.includes(notification.customCountReset)
  );
  setLocalStorageItem(
    `happNotificationsUnread#${appId}`,
    unreadNotificationsCleared
  );
}

export function validateNotifications(
  notifications: Array<HappNotification>
): Array<HappNotification> {
  const validateNotification = (notification: HappNotification) => {
    const { title, body, urgency, icon_file_name, timestamp } = notification;
    const validUrgencyLevels = ["low", "medium", "high"];

    if (typeof title !== "string") {
      throw new Error(
        "Received a notification with a title that's not of type string."
      );
    }
    if (typeof body !== "string") {
      throw new Error(
        "Received a notification with a body that's not of type string."
      );
    }
    if (!validUrgencyLevels.includes(urgency)) {
      throw new Error(
        "Received a notification with an invalid urgency level. Valid urgency levels are ['low', 'medium', 'high']."
      );
    }
    if (icon_file_name && typeof icon_file_name !== "string") {
      throw new Error(
        "Received a notification an invalid icon_src attribute. Must be either of type string or undefined."
      );
    }
    if (typeof timestamp !== "number") {
      throw new Error(
        `Received a notification with a timestamp that's not a number: ${timestamp}`
      );
    }
    if (!isMillisecondTimestamp(timestamp)) {
      throw new Error(
        `Received a notification with a timestamp that's not in millisecond format: ${timestamp}`
      );
    }
  };

  notifications.forEach(validateNotification);
  return notifications;
}

const isMillisecondTimestamp = (timestamp: number): boolean => {
  const reference = 1690803917545;
  return !(timestamp / reference > 10 || reference / timestamp > 1.5);
};

export const getHappNotificationSettings = (
  installedAppId: InstalledAppId
): HappNotificationSettings => {
  const defaultSettings = {
    allowOSNotification: true,
    showInSystray: true,
    showInLauncherView: true,
    showInFeed: true,
  };
  const happNotificationSettingsJson = getLocalStorageItem(
    `happNotificationSettings#${installedAppId}`
  );
  return happNotificationSettingsJson || defaultSettings;
};

export const setHappNotificationSettings = (
  installedAppId: InstalledAppId,
  settings: HappNotificationSettings
): void => {
  setLocalStorageItem(`happNotificationSettings#${installedAppId}`, settings);
};
```

2023-09-30 12:26 UTC, mrruby commented on src/views/Home.vue
> +    async openBackgroundWindows(apps: Array<HolochainAppInfo>) {
Maybe something like this here:
    
     ```
      const openInvisibleWindow = async (app: HolochainAppInfo) => {
        const appId = app.webAppInfo.installed_app_info.installed_app_id;
        const notificationSettings: HappNotificationSettings = getHappNotificationSettings(appId);
        return Object.values(notificationSettings).some((e) => !!e) ?
          invoke("open_app_ui", { appId, holochainId: app.holochainId, visible: false }) :
          Promise.resolve();
      };
      await Promise.all(apps.map(openInvisibleWindow));
      ```

2023-09-30 12:26 UTC, mrruby commented on src/store/index.ts
> +    },
How about?

```
      const getNotificationState = (key: string) => {
        const appId = key.slice(24);
        return { [appId]: readUnreadHappNotifications(appId) };
      };

      const isNotificationKey = (key: string) =>
        key.includes("happNotificationsUnread#");

      const notificationState = Object.keys(localStorage)
        .filter(isNotificationKey)
        .reduce((acc, key) => ({ ...acc, ...getNotificationState(key) }), {});

      console.log("### LOADING Notificationstate");
      console.log("notificationState: ", notificationState);

      state.notificationState = { ...state.notificationState, ...notificationState };
      ```

2023-09-30 12:26 UTC, mrruby commented on api_scripts/src/index.ts
> +});
How about:

```

const invokeTauriCommand = async (command: string, params: any) => {
  try {
    await invoke(command, params);
  } catch (e) {
    console.error(`Failed to invoke tauri command '${command}': `, e);
  }
}

window.__HC_LAUNCHER_API__ = {
  notify: (notifications: Array<HappNotification>) => {
    const appId = window.__HC_LAUNCHER_ENV__.INSTALLED_APP_ID;
    invokeTauriCommand("notify_tauri", { notifications, appId });
  },
  resetNotificationCount: (notificationIds: Array<NotificationId>) => {
    const appId = window.__HC_LAUNCHER_ENV__.INSTALLED_APP_ID;
    invokeTauriCommand("reset_happ_notification_count", { appId, notificationIds });
  },
};

window.addEventListener("focus", () => {
  const appId = window.__HC_LAUNCHER_ENV__.INSTALLED_APP_ID;
  invokeTauriCommand("clear_happ_notifications", { appId });
});

```

2023-10-02 20:13 UTC, matthme commented on src/utils.ts
>  }
agreed. Just pushed a commit to improve that

2023-10-02 20:14 UTC, matthme commented on src/views/Home.vue
> +    async openBackgroundWindows(apps: Array<HolochainAppInfo>) {
Hmm...I just tried it and to be honest I don't think it looks more cleaner/readable to define a function within a function...I'd prefer to leave it as it is.

2023-10-02 20:21 UTC, matthme commented on src/store/index.ts
> +    },
Defining functions only makes sense to me if the same piece of code is being used at different places across the code base, i.e. when it helps to prevent/reduce code repetition. That's not the case here so it seems obsolete/unnecessarily verbose to me to define functions here.

2023-10-02 20:28 UTC, matthme commented on api_scripts/src/index.ts
> +});
Agreed. Here it makes sense to me to define a function as it reduces code repetition (especially if more such commands will likely be added to the API in the future).

2023-10-03 08:59 UTC, mrruby commented on src/store/index.ts
> +    },
ok how about just:
```
  const notificationState = Object.keys(localStorage)
        .filter(key => key.includes("happNotificationsUnread#"))
        .reduce((acc, key) => {
            const appId = key.slice(24);
            return {
                ...acc,
                [appId]: readUnreadHappNotifications(appId)
            };
        }, {});
    state.notificationState = notificationState;
    ```

2023-10-03 09:08 UTC, mrruby commented on src/views/Home.vue
> +    async openBackgroundWindows(apps: Array<HolochainAppInfo>) {
ok agree, let's keep it as it is

2023-10-03 09:25 UTC, matthme commented on src/store/index.ts
> +    },
This would be way less efficient. My current solution only goes through the array once with the `forEach` method. Your solution goes through the array first with `filter`, then through the filtered array with `reduce` and then for each operation within `reduce` it also uses the spread operator which itself goes through the array.

2023-10-03 09:27 UTC, mrruby commented on src/store/index.ts
> +    },
ok let's leave it also

2023-10-03 10:34 UTC, mrruby approved these changes

2023-10-09 09:17 UTC, merged